# Sever Info
server:
  port: 5050

# Spring Info
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/businessCard
    username: root
    password: k76639950
# MyBatis Info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  prefix: ''
# MyBatis 설정
  mapper-locations: classpath:mapper/*.xml
