# Sever Info
server:
  port: 5050

# Spring Info
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/businessCard
    username: root
    password: k76639950
# MyBatis Info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  prefix: ''
# MyBatis 설정
  mapper-locations: classpath:mapper/*.xml
jwt:
  secret: ZWxlY3Ryb25pYy1idXNpbmVzcy1jYXJkLXNlY3JldC1rZXk=
  header: Authorization
  token-validity-in-seconds: 86400
  temp: electronic-business-card-secret-key
